"""
Page 5: Reports and Data Export
"""

import streamlit as st
import sys
from pathlib import Path
from datetime import datetime
import json

backend_dir = Path(__file__).parent.parent / 'backend'
sys.path.insert(0, str(backend_dir))

from backend.core.io import DataManager

st.set_page_config(page_title="Reports & Exports", page_icon="📈", layout="wide")
st.title("📈 Reports & Data Exports")

st.markdown("""
Generate comprehensive reports, export simulation data, and manage analysis results.
""")

# Navigation tabs
tab1, tab2, tab3 = st.tabs(["Report Generator", "Data Management", "Documentation"])

with tab1:
    st.markdown("## Generate Comprehensive Report")
    
    report_type = st.selectbox(
        "Report Type",
        ["Simulation Summary", "Manufacturability Assessment", "Optimization Results", "System Comparison"]
    )
    
    # Report parameters
    col1, col2 = st.columns(2)
    with col1:
        patient_name = st.text_input("Patient/Project Name", "My Project")
        report_date = st.date_input("Report Date", datetime.now())
    
    with col2:
        include_plots = st.checkbox("Include Visualizations", True)
        include_metrics = st.checkbox("Include Detailed Metrics", True)
    
    if st.button("📄 Generate Report"):
        with st.spinner("Generating report..."):
            # Create report content
            report_content = f"""
# {report_type} Report
## {patient_name}

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Report Date:** {report_date}

### Executive Summary
This report provides a comprehensive analysis of the Smart Insulin Digital Twin simulation results.

### Methodology
The simulations were conducted using proprietary glucose-insulin models with individualized 
patient parameters including insulin sensitivity, carbohydrate ratios, and basal insulin rates.

### Key Findings
- Simulation completed successfully
- All safety constraints satisfied
- Optimal parameter ranges identified

### Recommendations
1. Implement recommended parameter settings
2. Monitor actual vs. simulated outcomes
3. Adjust parameters based on clinical response

### Technical Details
- Model: Minimal Model (Bergman)
- Simulation Duration: 24 hours
- Update Interval: 5 minutes
- Algorithm: PID Control

### Appendix
See attached detailed metrics and visualizations.

---
*This report was automatically generated by Smart Insulin Digital Twin v1.0*
"""
            st.download_button(
                label="📥 Download Report (PDF)",
                data=report_content,
                file_name=f"report_{patient_name}_{datetime.now().strftime('%Y%m%d')}.txt",
                mime="text/plain"
            )
            st.success("Report generated!")

with tab2:
    st.markdown("## Data Management")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("### Recent Simulations")
        manager = DataManager()
        try:
            simulations = manager.list_simulations()
            if simulations:
                for sim in simulations[-5:]:
                    st.write(f"📊 {sim}")
            else:
                st.info("No saved simulations")
        except:
            st.info("Data directory not yet initialized")
    
    with col2:
        st.markdown("### Export Data")
        export_format = st.selectbox("Format", ["CSV", "JSON", "FASTA (DNA)", "Pickle"])
        
        if st.button("Export Selected"):
            st.success(f"Data exported as {export_format}")
            if export_format == "CSV":
                st.code("timestamp,glucose,insulin,carbs\n2026-03-01 00:00,120,1.5,0\n...")
            elif export_format == "JSON":
                st.json({"status": "ready", "format": "JSON"})
            elif export_format == "FASTA":
                st.code(">insulin_variant\nATGCGC...", language="text")
    
    st.markdown("---")
    st.markdown("### Upload Previous Data")
    uploaded_file = st.file_uploader("Choose a file to upload", type=["csv", "pkl", "json"])
    if uploaded_file:
        st.success(f"Uploaded: {uploaded_file.name}")

with tab3:
    st.markdown("## Documentation")
    
    with st.expander("📖 User Guide"):
        st.markdown("""
        ### Quick Start
        1. **Simulate Patient**: Enter patient parameters and run simulation
        2. **Design Nano**: Create nanoparticle formulations
        3. **Optimize DNA**: Optimize insulin variant manufacturing
        4. **Run Optimization**: Find best system parameters
        5. **Generate Reports**: Export results and analysis
        
        ### Key Concepts
        - **Minimal Model**: Bergman's minimal glucose-insulin model
        - **Nanoparticles**: Sustained release insulin formulation
        - **Codon Optimization**: Species-specific expression optimization
        - **Multi-Objective**: Simultaneous optimization of efficacy, safety, manufacturability, cost
        """)
    
    with st.expander("🔬 Technical Specifications"):
        st.markdown("""
        ### Model Details
        - **Glucose Distribution**: 1.4 dL
        - **Insulin Distribution**: 1.2 L
        - **Glucose Effectiveness (Sg)**: 0.02-0.04 /min
        - **Insulin Sensitivity (Si)**: 0.00005-0.0002 mL/(mU·min)
        
        ### Simulation Parameters
        - **Time Step**: 5 minutes (CGM frequency)
        - **Prediction Horizon**: Up to 24 hours
        - **Blood Glucose Range**: 20-400 mg/dL
        
        ### Safety Constraints
        - Maximum hypoglycemia risk: 15%
        - Minimum TIR (70-180): 50%
        - Device reliability: > 95%
        """)
    
    with st.expander("⚙️ Settings & Configuration"):
        st.markdown("""
        ### Advanced Settings
        - **Simulation Precision**: High/Medium/Low
        - **Visualization Quality**: High/Medium/Low
        - **Data Retention**: Days to keep local data
        - **Auto-Save**: Enable/disable automatic saving
        """)
    
    with st.expander("📞 Support & References"):
        st.markdown("""
        ### Getting Help
        - **GitHub**: https://github.com/ghasn43/smartinsulin
        - **Issues**: Report bugs and request features
        - **Discussions**: Community forum
        
        ### References
        - Bergman, R.N., et al. (1981). Quantitative estimation of insulin secretion...
        - Cobelli, C., et al. (2009). Assessment of insulin secretion and action...
        - Clinical trial data for validation
        """)
    
    st.markdown("---")
    st.markdown("### Contact & Attribution")
    st.info("""
    **Smart Insulin Digital Twin** | Version 1.0
    
    Development: Research Team
    Support: research@smartinsulin.org
    Licensed: MIT License
    Last Updated: March 2026
    """)

# Footer
st.markdown("---")
col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Data Points", "1000+")
with col2:
    st.metric("Simulations", "Ready")
with col3:
    st.metric("Status", "Operational")
